# Generated by Django 3.2.7 on 2022-01-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=12)),
                ('mid', models.CharField(max_length=12)),
                ('level', models.IntegerField(null=True)),
                ('melement', models.CharField(max_length=1024, null=True)),
                ('mtitle', models.CharField(max_length=1024, null=True)),
                ('mclass', models.CharField(max_length=1024, null=True)),
                ('mdataoption', models.CharField(max_length=1024, null=True)),
                ('mstyle', models.CharField(max_length=1024, null=True)),
                ('msrc', models.CharField(max_length=1024, null=True)),
                ('mhref', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
