# Generated by Django 3.2.7 on 2022-01-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=30, null=True)),
                ('birth', models.CharField(max_length=30, null=True)),
                ('age', models.CharField(max_length=30, null=True)),
                ('nation', models.CharField(max_length=30, null=True)),
                ('c01', models.CharField(max_length=30, null=True)),
                ('c02', models.CharField(max_length=30, null=True)),
                ('c03', models.CharField(max_length=30, null=True)),
                ('c04', models.CharField(max_length=30, null=True)),
                ('c05', models.CharField(max_length=30, null=True)),
                ('c06', models.CharField(max_length=30, null=True)),
                ('c07', models.CharField(max_length=30, null=True)),
                ('c08', models.CharField(max_length=30, null=True)),
                ('c09', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
