# Generated by Django 3.2.7 on 2022-01-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0002_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuedrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(null=True, unique=True)),
                ('attendSchool', models.CharField(max_length=30, null=True)),
                ('grade', models.CharField(max_length=30, null=True)),
                ('situation', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stufamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('appellation', models.CharField(max_length=30, null=True)),
                ('idcard', models.CharField(max_length=18, null=True)),
                ('job', models.CharField(max_length=30, null=True)),
                ('duties', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stuinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=30, null=True)),
                ('birth', models.CharField(max_length=30, null=True)),
                ('age', models.CharField(max_length=30, null=True)),
                ('nation', models.CharField(max_length=30, null=True)),
                ('photo', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('register', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('idcard', models.CharField(max_length=18, null=True)),
                ('disabilityid', models.CharField(max_length=30, null=True)),
                ('classification', models.CharField(max_length=30, null=True)),
                ('grade', models.CharField(max_length=30, null=True)),
                ('disease', models.CharField(max_length=30, null=True)),
                ('paerntal', models.CharField(max_length=30, null=True)),
                ('family', models.CharField(max_length=30, null=True)),
                ('remarks', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stuskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillid', models.IntegerField(null=True, unique=True)),
                ('num', models.IntegerField(null=True, unique=True)),
                ('item', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stuviability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(null=True, unique=True)),
                ('skillid', models.IntegerField(null=True, unique=True)),
                ('score', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='studentinfo',
        ),
    ]
