# Generated by Django 3.2.7 on 2022-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0003_auto_20220110_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuskill',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stuskill',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
