# Generated by Django 3.2.7 on 2022-01-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0004_auto_20220110_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuskill',
            name='item',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
