# Generated by Django 3.2.7 on 2022-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0005_alter_stuskill_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='strengthen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(null=True, unique=True)),
                ('num', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=80, null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stuskill',
            old_name='item',
            new_name='text',
        ),
    ]
