# Generated by Django 3.2.7 on 2022-01-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0006_auto_20220110_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schooltype',
            new_name='sch_type',
        ),
        migrations.RenameModel(
            old_name='stuedrol',
            new_name='stu_edrol',
        ),
        migrations.RenameModel(
            old_name='stufamily',
            new_name='stu_family',
        ),
        migrations.RenameModel(
            old_name='stuinfo',
            new_name='stu_info',
        ),
        migrations.RenameModel(
            old_name='stuviability',
            new_name='stu_viability',
        ),
        migrations.RenameModel(
            old_name='stuskill',
            new_name='zb_skill',
        ),
        migrations.RenameModel(
            old_name='strengthen',
            new_name='zb_strengthen',
        ),
    ]
