# Generated by Django 3.2.7 on 2022-01-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0007_auto_20220111_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stu_edrol',
            new_name='stu_enrol',
        ),
    ]
