# Generated by Django 3.2.7 on 2022-01-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjxt', '0008_rename_stu_edrol_stu_enrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zb_skill',
            new_name='zb_viability',
        ),
    ]
